CALIB_STAGE_LOWMAG = 'calib_stage_lowmag.pickle'
CALIB_BEAMSHIFT = 'calib_beamshift.pickle'
CALIB_BRIGHTNESS = 'calib_brightness.pickle'
CALIB_DIFFSHIFT = 'calib_diffshift.pickle'
CALIB_DIRECTBEAM = 'calib_directbeam.pickle'

CALIB_IS1_FOC = 'ISCalib_foc.pkl'
CALIB_IS1_DEFOC = 'ISCalib.pkl'
CALIB_IS2_FOC = 'IS2Calib_foc.pkl'
CALIB_IS2_DEFOC = 'IS2Calib.pkl'
CALIB_BEAMSHIFT_DP = 'BSCalib_foc.pkl'
CALIB_BEAMSHIFT_DP_DEFOC = 'BSCalib_defoc.pkl'
CALIB_STAGE = 'CalibStage.pkl'
